---
# tasks file for nginx
- name: Install required packages
  yum: name=nginx

- name: Start nginx service
  service: name=nginx state=started

- name: Create index.html file
  template: src=index.html.j2 
    dest=/usr/share/nginx/html/index.html 
    owner=nginx 
    group=nginx