---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    stack_name: frolstack
    region: eu-west-1
    owner: frol
    ami_id: ami-bb9a6bc2
    keyname: inilap

  - name: Create App
    action: cloudformation
      stack_name={{ stack_name }}-app
      state=present
      region="{{region}}"
      template=https://s3-eu-west-1.amazonaws.com/cfntemp/ansible_cf.template